language: node_js

node_js:
    - "4"

before_script:
    - ./deploy.sh
    - npm install -g grunt-cli
    - npm install -g bower
    - bower install

deploy:
    - provider: script
      script: ./deploy.sh
      on:
        tags: true
        all_branches: true
      skip_cleanup: true
